<?php
/**
 * @file
 * Rewrites the comment permalink to use fragment for SEO purposes.
 */

/**
 * Implements hook_autoload_info().
 */
function comment_fragment_autoload_info() {
  return array(
    'comment_fragment_handler_field_comment_link' => 'views/comment_fragment_handler_field_comment_link.inc',
    'comment_fragment_handler_field_comment_path' => 'views/comment_fragment_handler_field_comment_path.inc',
  );
}

/**
 * Implements hook_entity_info_alter().
 */
function comment_fragment_entity_info_alter(&$entity_info) {
  $entity_info['comment']['uri callback'] = 'comment_fragment_uri';
}

/**
 * Entity URI callback.
 */
function comment_fragment_uri($comment) {
  $node = node_load($comment->nid);
  $page = comment_get_display_page($comment->cid, $node->type);

  $uri = array(
    'path' => 'node/' . $comment->nid,
    'options' => array('fragment' => 'comment-' . $comment->cid),
  );
  if ($page > 0) {
    $uri['options']['query']['page'] = $page;
  }
  return $uri;
}

/**
 * Implements hook_menu_alter().
 */
function comment_fragment_menu_alter(&$items) {
  $items['comment/%']['page callback'] = 'comment_fragment_permalink';
}

/**
 * Redirects comment links to the correct fragment depending on comment settings.
 *
 * @param $cid
 *   A comment identifier.
 * @return
 *   The comment listing set to the page on which the comment appears.
 */
function comment_fragment_permalink($cid) {
  if ($comment = comment_load($cid)) {
    $uri = comment_fragment_uri($comment);
    backdrop_goto($uri['path'], $uri['options']);
  }

  return MENU_NOT_FOUND;
}

/**
 * Prepares variables for comment templates.
 *
 * @see comment.tpl.php
 */
function comment_fragment_preprocess_comment(&$variables) {
  $comment = $variables['elements']['#comment'];
  $uri = comment_fragment_uri($comment);
  $uri['options'] += array('attributes' => array('class' => array('permalink'), 'rel' => 'bookmark'));

  // Replace the links automatically printed in the comments.
  $variables['permalink'] = l(t('Permalink'), $uri['path'], $uri['options']);
  $variables['permalink_path'] = $uri['path'] . "#" . $uri['options']['fragment'];
}

/**
 * Implements hook_views_api().
 */
function comment_fragment_views_api() {
  return array(
    'api' => 3,
    'path' => backdrop_get_path('module', 'comment_fragment') . '/views',
  );
}
